spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true # 是否确认发送的消息已经被消费

rabbitmq:
  queue:
    msg: spring-boot-queue-msg
    user: spring-boot-queue-user